# Generated by Django 5.1.4 on 2024-12-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка на магазин')),
                ('key', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Ключ')),
                ('export_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка для клиента')),
            ],
            options={
                'verbose_name': 'Клиента',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
